APIMVC/Models/Color.cs
namespace APIMVC.Models
{

    public class Color
    {
        public int page { get; set; }
        public int per_page { get; set; }
        public int total { get; set; }
        public int total_pages { get; set; }
        public CDatum[] data { get; set; }
        public CSupport support { get; set; }
    }

    public class CSupport
    {
        public string url { get; set; }
        public string text { get; set; }
    }

    public class CDatum : DogPicture
    {
        public int id { get; set; }
        public string name { get; set; }
        public int year { get; set; }
        public string color { get; set; }
        public string pantone_value { get; set; }
    }

}

APIMVC/Models/DogPicture.cs
namespace APIMVC.Models
{

    public class DogPicture
    {
        public string message { get; set; }
        public string status { get; set; }
    }

}

APIMVC/Models/Employee.cs
using Microsoft.EntityFrameworkCore;

namespace APIMVC.Models
{

    public class Employee
    {
        public int page { get; set; }
        public int per_page { get; set; }
        public int total { get; set; }
        public int total_pages { get; set; }
        public Datum[] data { get; set; }
        public Support support { get; set; }
    }

    public class Support
    {
        public string url { get; set; }
        public string text { get; set; }
    }

    public class Datum : Message
    {
        public int id { get; set; }
        public string email { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string avatar { get; set; }
    }
}

APIMVC/Models/ErrorViewModel.cs
namespace APIMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

APIMVC/Models/Guru.cs
namespace APIMVC.Models
{

    public class Guru
    {
        public string[] data { get; set; }
    }

}

APIMVC/Models/Joke.cs
namespace APIMVC.Models
{

    public class Joke
    {
        public string type { get; set; }
        public string setup { get; set; }
        public string punchline { get; set; }
        public int id { get; set; }
    }

}

APIMVC/Models/Message.cs
namespace APIMVC.Models
{
    public class Message
    {
        public string message { get; set; }
    }
}

APIMVC/Models/Sun.cs
namespace APIMVC.Models
{

    public class Sun : Joke
    {
        public Results results { get; set; }
        public string status { get; set; }
        public string tzid { get; set; }
    }

    public class Results
    {
        public string sunrise { get; set; }
        public string sunset { get; set; }
        public string solar_noon { get; set; }
        public string day_length { get; set; }
        public string civil_twilight_begin { get; set; }
        public string civil_twilight_end { get; set; }
        public string nautical_twilight_begin { get; set; }
        public string nautical_twilight_end { get; set; }
        public string astronomical_twilight_begin { get; set; }
        public string astronomical_twilight_end { get; set; }
    }

}

APIMVC/Controllers/ColorController.cs
using APIMVC.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace APIMVC.Controllers
{
    public class ColorController : Controller
    {
        private readonly IColor colorRep;

        public ColorController(IColor colorRep)
        {
            this.colorRep = colorRep;
        }
        // GET: ColorController
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> List()
        {
            var colors = await colorRep.GetAllColors();
            return View(colors);
        }

        // GET: ColorController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ColorController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ColorController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ColorController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ColorController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ColorController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ColorController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

APIMVC/Controllers/EmployeeController.cs
using APIMVC.Data;
using APIMVC.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace APIMVC.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployee employeeRepo;

        public EmployeeController(IEmployee employeeRepo)
        {
            this.employeeRepo = employeeRepo;
        }

        public async Task<ActionResult> List()
        {
            var users = await employeeRepo.GetAllEmployees();
            return View(users);
        }

        
        public async Task<ActionResult> Contact(int? id)
        {
            var employee = await employeeRepo.GetEmployeeById(id);
            return View(employee);
        }

    }
}

APIMVC/Controllers/GuruController.cs
using APIMVC.Data;
using Microsoft.AspNetCore.Mvc;

namespace APIMVC.Controllers
{
    public class GuruController : Controller
    {
        private readonly IGuru guruRepo;

        public GuruController(IGuru guruRepo) 
        {
            this.guruRepo = guruRepo;
        }
        public async Task<IActionResult> ListPartners()
        {
            var guruProviders = await guruRepo.GetPartners();
            return View(guruProviders);
        }
    }
}

APIMVC/Controllers/HomeController.cs
using APIMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Text.Json;

namespace APIMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var sun = await GetSunInfo();
            var joke = await GetRandomJoke();
            sun.setup = joke.setup;
            sun.punchline = joke.punchline;
            return View(sun);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<Sun> GetSunInfo()
        {
            Sun sun = new Sun();
            HttpClient client = new HttpClient();

            HttpResponseMessage response = await client.GetAsync("https://api.sunrise-sunset.org/json?lat=59.329380&lng=18.068710&date=today");

            if (response.IsSuccessStatusCode)
            {
                var result = response.Content.ReadAsStringAsync().Result;
                sun = JsonSerializer.Deserialize<Sun>(result);

                return sun;
            }
            else
            {
                return null;
            }
        }

        public async Task<Joke> GetRandomJoke()
        {
            Joke joke = new Joke();
            HttpClient client = new HttpClient();

            HttpResponseMessage response = await client.GetAsync("https://official-joke-api.appspot.com/random_joke");

            if (response.IsSuccessStatusCode)
            {
                var result = response.Content.ReadAsStringAsync().Result;
                joke = JsonSerializer.Deserialize<Joke>(result);

                return joke;
            }
            else
            {
                return null;
            }
        }



    }
}

APIMVC/Views/Color/List.cshtml
@model List<APIMVC.Models.CDatum>

@{
    ViewData["Title"] = "List";
}
@if (Model != null)
{
    <div class="overlay mt-5 pt-5">
        <h1>Colors</h1>
        <div class="row text-center">

            @foreach (var item in Model)
            {
                <div class="col-md-4 color-card pt-2 m-1">
                    <div style="background-color: @item.color; box-shadow: 0 0 25px @item.color; border: 2px solid black;">

                        <h2>@Html.DisplayFor(modelItem => item.name)</h2>

                        <h1>@Html.DisplayFor(modelItem => item.color)</h1>
                        <img src="@item.message" width="180" height="150" />

                        <div class="mt-4">
                            <h5>Pantone Value</h5>
                            <h3>@Html.DisplayFor(modelItem => item.pantone_value)</h3>
                            <p>Year: @Html.DisplayFor(modelItem => item.year)</p>
                        </div>
                    </div>
                </div>
            }

        </div>



    </div>
}
else
{
    <h1>No colors found</h1>
}

APIMVC/Views/Employee/Contact.cshtml
@model APIMVC.Models.Datum

@{
    ViewData["Title"] = "Details";
}
<div class="overlay mt-5">
<div class="back">
        <a asp-action="List"> <i class="fa-solid fa-caret-left"></i> Back to List</a>
</div>
<div class="text-center pt-5 mt-5">
    <div class="info col-md-4">
        <h1>@Html.DisplayFor(model => model.first_name) @Html.DisplayFor(model => model.last_name)</h1>
        <img src="@Model.avatar" width="350" />
            <p class="mt-4">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. 
               At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
    </div>
    <div class="email-btn col-md-4 mt-5">
        <a href="mailto:@Model.email" class="btn">Contact</a>
    </div>
</div>
</div>

APIMVC/Views/Employee/List.cshtml
@model List<APIMVC.Models.Datum>

@{
    ViewData["Title"] = "List";
}
<div class="overlay mt-5 pt-5">
@if (Model != null)
{
        <h1>Employees</h1>
    <div class="row text-center">

        @foreach (var item in Model)
        {
            <div class="col-md-4">
                <div class="card p-3 m-4">
                   
                    <img src="@item.avatar" width="200" /> 

                    <h4 class="card-title">@Html.DisplayFor(modelItem => item.first_name) @Html.DisplayFor(modelItem => item.last_name)</h4>

                        <p class="fst-italic">"@Html.DisplayFor(modelItem => item.message)"</p>

                    <p class="mailto mt-2">@Html.ActionLink("Contact Me", "Contact", new { id = item.id })</p>
            
                </div>
            </div>
        }

    </div>
 
}
else
{
    <h1>No employees found</h1>
}
</div>

APIMVC/Views/Guru/ListPartners.cshtml
@model List<string>

@{
    ViewData["Title"] = "ListPartners";
}
<div class="overlay mt-5 pt-5">
@if (Model != null)
{


        <h1>Partners</h1>

        @foreach (var letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ")
        {
            var filteredItems = Model.Where(item => item.StartsWith(letter.ToString(), StringComparison.OrdinalIgnoreCase));
            if (filteredItems.Any())
            {
                <div class="dropdown">
                    <button class="partners"><h1>@letter</h1></button>
                    <div class="dropdown-content">
                        <ul>
                        @foreach (var item in filteredItems)
                        {
                           
                                <li>
                                    
                                    <a href="https://@item" target="_blank">@item</a>
                                </li>
                            
                        }
                        </ul>
                    </div>
                </div>
            }
        }

}
else
{
    <h1>Something went wrong.</h1>
    <p>We are working on it!</p>
}
</div>

APIMVC/Views/Home/Index.cshtml
@model APIMVC.Models.Sun

@{
    ViewData["Title"] = "Home Page";
}

@* <div class="text-center home">
    <img src="~/css/RNCity.jpg" />
    <h1 class="display-4">Welcome to RN Tech</h1>
</div> *@
<div class="home">
    <img src="~/css/RNCity.jpg" class="background-image" />
    <div class="text-center overlay mt-3">
        @* <h1 class="display-4">Welcome to RN Tech</h1> *@
        <h4>@Html.DisplayFor(modelitem => modelitem.setup) </h4>
        <h3>@Html.DisplayFor(modelitem => modelitem.punchline) </h3>
    </div>
</div>
<div class="sun">
    <h2>STHLM</h2>
    <h5>@Html.DisplayFor(modelitem => modelitem.results.sunrise) <i class="fa-regular fa-sun"></i></h5>
    <h5>@Html.DisplayFor(modelitem => modelitem.results.sunset) <i class="fa-regular fa-moon"></i></h5>
</div>

APIMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RN Tech</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/APIMVC.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/27b0f27f86.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/css/RNLogo.png" width="50px" /> RN Tech</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Employee" asp-action="List">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Color" asp-action="List">Colors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Guru" asp-action="ListPartners">Partners</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RN Technology AB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>